// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: process.env.REACT_APP_PRIVATE_ENDPOINT,
          region: 'us-east-2',
          defaultAuthMode: 'apiKey',
          apiKey: process.env.REACT_APP_PRIVATE_API_KEY
        }
    }
};

export default config;